[project]
name = "karukotha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "magnum>=21.0.1",
    "mangum>=0.17.0",
    "sqlmodel>=0.0.31",
]
[tool.setuptools]
packages = ["app"]
