[project]
name = "karukotha-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.17.2",
    "fastapi[standard]>=0.128.0",
    "mangum>=0.17.0",
    "sqlmodel>=0.0.31",
]
